### ISSUE TITLE
第二章跑不起来

### ISSUE THREAD

**Issue by CommanderXL** [island205/technode-tutorial#9]
+ question one:

入口文件app.js里面:
    
    var Controllers=require("./controllers"); //这个地方引用的是一个文件夹，会报错。
是不是应该直接改为引用文件夹里面的文件.然后调用其方法
    
    var Controllers=require("./controllers/user.js");

+ question two:

在router.js文件里面

    $locationProvider.html5Mode({
             enabled:true,
             requireBase:false,   //这个地方要配置下，否则会报错[$location:nobase]
    })

写到socket.io验证那个地方就写不下去了。仅仅实现了路由的请求，发送消息的内容实现不了。

**Comment by ylyujstu** [comment]
var Controllers=require("./controllers"); //这个地方引用的是一个文件夹，会报错。
确实会报错！

**Comment by island205** [comment]
麻烦把报错贴出来一下

**Comment by island205** [comment]
@CommanderXL @ylyujstu 请参看完整的第二章代码。

``` javascript
var Controllers=require("./controllers");
```

在 Node.js 中可以直接 `require` 一个文件夹，前提是这个文件夹下面有一个 `index.js` 文件，可以确认一下你的 `controllers` 文件夹下面是否已经有了一个 `index.js` 文件，内容是：

``` javascript
exports.User = require('./user')
exports.Message = require('./message')
```
